/**
 * -------------------------------------------------------------------------------------
 * LANG CONFIGURATION //////////////////////////////////////////////////////////////////
 * -------------------------------------------------------------------------------------
 */

const array_lang_value = {
	// fr : French
	"fr": { // French
		"HONO_BUTTON" : "Négocier le prix",
		"MODAL_TITLE" : "Négociez le prix qui vous convient le mieux pour",
		"MODAL_HOW_MUCH_DO_YOU_HAVE":"De combien disposez vous?",
		"MODAL_NEXT_BUTTON" : "Suivant",
		"MODAL_SEND_BUTTON" : "Envoyer",
		"MODAL_LEAVE_INFO" : "Laissez quelques informations pour être contacté plus tard par le vendeur",
		"MODAL_ASK_NUMBER" : "Numero de telephone(Facultatif)",
		"MODAL_LEAVE_MESSAGE_PLACEHOLDER" : "Laissez un court message au vendeur (pas plus de 100 lettres) Ex: Merci de me faire signe au plus tot.",
		"MODAL_MESSAGE_SENT_SUCCESS" : "Message envoyé avec succès!",
		"MODAL_INDICATION_MESSAGE1" : " Une interface de TCHAT est déjà disponible pour que vous echangier sur des détails suplémentaires avec le vendeur, vous pouvez y accéder pour en discutter en ",
		"MODAL_INDICATION_MESSAGE2" : "cliquant ici",
		"ALERT_YOURMONEY_TOO_SMALL1" : "Votre montant est trop bas, il vous reste ",
		"ALERT_YOURMONEY_TOO_SMALL2" : " essaie(s).",
		"EMAIL_HELLO_MESSAGE" : "Hello, nous avons une demande de négociation de prix sur votre article, voici les details",
		"EMAIL_INTITULE_ARTICLE" : "Produit",
		"EMAIL_INTITULE_AMOUNT" : "Prix",
		"EMAIL_INTITULE_PROPOSITION" : "Proposition",
		"EMAIL_INTITULE_EMAIL" : "Email",
		"EMAIL_INTITULE_NUMERO" : "Numéro de téléphone",
		"EMAIL_INTITULE_MESSAGE" : "Message",
		"EMAIL_JOIN_TCHAT_MESSAGE1" : "Vous pouvez rejoindre le client sur notre service de TCHAT gratuit, pour échanger gratuitement en ",
		"EMAIL_JOIN_TCHAT_MESSAGE2" : "cliquant ici",
		"FILL_CORRECTLY_FORMMAIL": "Remplissez correctement le formulaire."
	},
	"en": { //  English
		"HONO_BUTTON" : "Negotiate the price",
		"MODAL_TITLE" : "Negotiate the price that suits you best for",
		"MODAL_HOW_MUCH_DO_YOU_HAVE":"How much do you have?",
		"MODAL_NEXT_BUTTON" : "Next",
		"MODAL_SEND_BUTTON" : "Send",
		"MODAL_LEAVE_INFO" : "Leave some information to be contacted later by the seller",
		"MODAL_ASK_NUMBER" : "Phone number (Optional)",
		"MODAL_LEAVE_MESSAGE_PLACEHOLDER" : "Leave a short message to the seller (no more than 100 letters) Ex: Thank you to sign me as soon as possible.",
		"MODAL_MESSAGE_SENT_SUCCESS" : "Message sent successfully!",
		"MODAL_INDICATION_MESSAGE1" : " A TCHAT interface is already available for you to exchange on additional details with the seller, you can access to discuss it ",
		"MODAL_INDICATION_MESSAGE2" : "by clicking here",
		"ALERT_YOURMONEY_TOO_SMALL1" : "Your amount is too low, you have ",
		"ALERT_YOURMONEY_TOO_SMALL2" : " essays left.",
		"EMAIL_HELLO_MESSAGE" : "Hello, we have a price negotiation request on your item, here are the details",
		"EMAIL_INTITULE_ARTICLE" : "Product",
		"EMAIL_INTITULE_AMOUNT" : "Amount",
		"EMAIL_INTITULE_PROPOSITION" : "Proposal",
		"EMAIL_INTITULE_EMAIL" : "E-mail",
		"EMAIL_INTITULE_NUMERO" : "Phone number",
		"EMAIL_INTITULE_MESSAGE" : "Message",
		"EMAIL_JOIN_TCHAT_MESSAGE1" : "You can join the customer on our free TCHAT service, to exchange for free by ",
		"EMAIL_JOIN_TCHAT_MESSAGE2" : "clicking here",
		"FILL_CORRECTLY_FORMMAIL": "Please, fill correctly the form."
	},
	"sp":{ // Spanish
		"HONO_BUTTON" : "Negociar el precio",
		"MODAL_TITLE" : "Negocie el precio que más le convenga.",
		"MODAL_HOW_MUCH_DO_YOU_HAVE":"Cuanto tienes?",
		"MODAL_NEXT_BUTTON" : "Siguiente",
		"MODAL_SEND_BUTTON" : "Enviar",
		"MODAL_LEAVE_INFO" : "Deja alguna información para ser contactado más tarde por el vendedor.",
		"MODAL_ASK_NUMBER" : "Número de teléfono (opcional)",
		"MODAL_LEAVE_MESSAGE_PLACEHOLDER" : "Deje un mensaje breve para el vendedor (no más de 100 letras) Ej: Gracias por firmar lo antes posible.",
		"MODAL_MESSAGE_SENT_SUCCESS" : "Mensaje enviado con éxito!",
		"MODAL_INDICATION_MESSAGE1" : " Ya está disponible una interfaz TCHAT para que pueda intercambiar información adicional con el vendedor, puede acceder para discutirla haciendo ",
		"MODAL_INDICATION_MESSAGE2" : "clic aquí.",
		"ALERT_YOURMONEY_TOO_SMALL1" : "Tu cantidad es muy baja, te quedan ",
		"ALERT_YOURMONEY_TOO_SMALL2" : " ensayos.",
		"EMAIL_HELLO_MESSAGE" : "Hola, tenemos una solicitud de negociación de precio en su artículo, aquí están los detalles",
		"EMAIL_INTITULE_ARTICLE" : "Producto",
		"EMAIL_INTITULE_AMOUNT" : "Cantidad",
		"EMAIL_INTITULE_PROPOSITION" : "Propuesta",
		"EMAIL_INTITULE_EMAIL" : "E-mail",
		"EMAIL_INTITULE_NUMERO" : "Número de teléfono",
		"EMAIL_INTITULE_MESSAGE" : "Mensaje",
		"EMAIL_JOIN_TCHAT_MESSAGE1" : "Puede unirse al cliente en nuestro servicio gratuito TCHAT, para intercambiar de forma gratuita haciendo ",
		"EMAIL_JOIN_TCHAT_MESSAGE2" : "clic aquí",
		"FILL_CORRECTLY_FORMMAIL": "Please, fill correctly the form."
	},
	"ge":{ //  German
		"HONO_BUTTON" : "Verhandeln Sie den Preis",
		"MODAL_TITLE" : "Verhandeln Sie den Preis, der am besten zu Ihnen passt",
		"MODAL_HOW_MUCH_DO_YOU_HAVE":"Wie viel hast du?",
		"MODAL_NEXT_BUTTON" : "Weiter",
		"MODAL_SEND_BUTTON" : "senden",
		"MODAL_LEAVE_INFO" : "Hinterlassen Sie einige Informationen, um später vom Verkäufer kontaktiert zu werden",
		"MODAL_ASK_NUMBER" : "Telefonnummer (optional)",
		"MODAL_LEAVE_MESSAGE_PLACEHOLDER" : "Hinterlassen Sie eine kurze Nachricht an den Verkäufer (nicht mehr als 100 Buchstaben) Bsp: Vielen Dank, dass Sie mich so bald wie möglich unterschreiben.",
		"MODAL_MESSAGE_SENT_SUCCESS" : "Nachricht erfolgreich gesendet!",
		"MODAL_INDICATION_MESSAGE1" : " Eine TCHAT-Schnittstelle steht Ihnen bereits zur Verfügung, um weitere Details mit dem Verkäufer auszutauschen. Sie können diese hier einsehen, indem Sie hier ",
		"MODAL_INDICATION_MESSAGE2" : "klicken",
		"ALERT_YOURMONEY_TOO_SMALL1" : "Ihr Betrag ist zu niedrig, Sie haben noch ",
		"ALERT_YOURMONEY_TOO_SMALL2" : " Aufsätze.",
		"EMAIL_HELLO_MESSAGE" : "Hallo, wir haben eine Preisverhandlung Anfrage auf Ihren Artikel, hier sind die Details",
		"EMAIL_INTITULE_ARTICLE" : "Produkt",
		"EMAIL_INTITULE_AMOUNT" : "Menge",
		"EMAIL_INTITULE_PROPOSITION" : "Vorschlag",
		"EMAIL_INTITULE_EMAIL" : "E-Mail",
		"EMAIL_INTITULE_NUMERO" : "Telefonnummer",
		"EMAIL_INTITULE_MESSAGE" : "Nachricht",
		"EMAIL_JOIN_TCHAT_MESSAGE1" : "Sie können dem Kunden auf unserem kostenlosen TCHAT-Dienst beitreten, um kostenlos umzutauschen, indem ",
		"EMAIL_JOIN_TCHAT_MESSAGE2" : "Sie hier klicken",
		"FILL_CORRECTLY_FORMMAIL": "Please, fill correctly the form."
	}
};

export default array_lang_value;